version: '3.8'
services:
  db:
    image: postgres:12.1
    volumes:
      - pgdata12:/var/lib/postgresql12/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    command: --fsync=off -c 'shared_preload_libraries="pg_stat_statements"' -c 'pg_stat_statements.track=all'
    ports:
      - "6543:5432"

  migrations:
    build:
      context: ..
      dockerfile: docker/Dockerfile.local
    image: $DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG$DOCKER_BRANCH_NAME
    environment:
      - MIX_ENV
    env_file:
      - envfiles/local.env
    depends_on:
      - db
    command: mix ecto.setup
    entrypoint:
      - /app/docker/scripts/wait-for-it.sh
      - db:5432
      - --timeout=0
      - --strict
      - --

  app:
    image: $DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG$DOCKER_BRANCH_NAME
    environment:
      - MIX_ENV
      - GITHUB_TOKEN
    env_file:
      - envfiles/local.env
    restart: on-failure
    stdin_open: true
    container_name: app
    tty: true
    depends_on:
      migrations:
        condition: "service_completed_successfully"
    ports:
      - "4001:4000"
    command: $APP_COMMAND
    volumes:
      - '../lib:/app/lib'
      - '../priv:/app/priv'
      - '../secrets:/app/secrets'
      - '../test:/app/test'

volumes:
  pgdata12:
