name: First workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: docker-compose build
        run: make build

      - name: Start env
        run: make env-start

      - name: Wait for start
        run: while true; do curl -sSf http://localhost:4001 && break || sleep 1; done

      - name: Test
        run: make test