name: Pull Request

#on: [pull_request]
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: docker-compose build
        run: make build

      - name: Start env
        run: APP_COMMAND='tail -f /dev/null' make env-start

#      - name: Wait for start
#        run: while true; do curl -sSf http://localhost:4001 > /dev/null 2&>1 && break || echo “Waiting to elixir server” && sleep 10; done

      - name: Test
        run: make test
