name: pr

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: docker-compose build
        run: make build

      - name: Start env
        run: APP_COMMAND='tail -f /dev/null' make env-start

      - name: Test
        run: make test
